messages:
  prefix: "§8[§3Social§8] "
  friend_request_sent: "§8[§3Social§8] §aDemande d'ami envoyée à §b{player}§a !"
  friend_request_received: "§8[§3Social§8] §aVous avez reçu une demande d'ami de §b{player}§a !"
  already_sent_request: "§8[§3Social§8] §eVous avez déjà envoyé une demande à ce joueur."
  cannot_add_self: "§8[§3Social§8] §cVous ne pouvez pas vous ajouter vous-même."
  friend_request_accepted: "§8[§3Social§8] §aVous avez accepté la demande d'ami de §b{player}§a !"
  your_request_accepted: "§8[§3Social§8] §a§b{player}§a a accepté votre demande d'ami !"
  no_request_from_player: "§8[§3Social§8] §cAucune demande d'ami de ce joueur."
  friend_request_declined: "§8[§3Social§8] §cVous avez refusé la demande d'ami de §b{player}§c."
  your_request_declined: "§8[§3Social§8] §c§b{player}§c a refusé votre demande d'ami."
  friend_removed: "§8[§3Social§8] §cVous avez retiré §b{player}§c de vos amis."
  removed_by_friend: "§8[§3Social§8] §c§b{player}§c vous a retiré de ses amis."
  not_in_friends: "§8[§3Social§8] §eCe joueur n'est pas dans votre liste d'amis."
  already_blocked: "§8[§3Social§8] §eCe joueur est déjà bloqué."
  player_blocked: "§8[§3Social§8] §aVous avez bloqué §b{player}§a."
  you_are_blocked: "§8[§3Social§8] §cVous avez été bloqué par §b{player}§c."
  player_unblocked: "§8[§3Social§8] §aVous avez débloqué §b{player}§a."
  you_are_unblocked: "§8[§3Social§8] §aVous avez été débloqué par §b{player}§a."
  not_in_blocked: "§8[§3Social§8] §eCe joueur n'est pas dans votre liste de joueurs bloqués."
  friends_list_header: "§8[§3Social§8] §6--- Liste de vos amis ---"
  friends_list_empty: "§8[§3Social§8] §7Vous n'avez pas d'amis pour le moment."
  friends_list_entry: "§8[§3Social§8] §a- §b{player}"
  friends_list_footer: "§8[§3Social§8] §6------------------------"
  invalid_argument: "§8[§3Social§8] §cArgument invalide. Utilisez §e/friends <invite|accept|decline|remove|block|unblock|list> [joueur]"
  only_players: "§8[§3Social§8] §cSeuls les joueurs peuvent utiliser cette commande."
