messages:
  prefix: "§8[§3Social§8] "
  friend_request_sent: "§aDemande d'ami envoyée à §b{player}§a !"
  friend_request_received: "§aVous avez reçu une demande d'ami de §b{player}§a !"
  already_sent_request: "§eVous avez déjà envoyé une demande à ce joueur."
  cannot_add_self: "§cVous ne pouvez pas vous ajouter vous-même."
  friend_request_accepted: "§aVous avez accepté la demande d'ami de §b{player}§a !"
  your_request_accepted: "§b{player}§a a accepté votre demande d'ami !"
  no_request_from_player: "§cAucune demande d'ami de ce joueur."
  friend_request_declined: "§cVous avez refusé la demande d'ami de §b{player}§c."
  your_request_declined: "§c§b{player}§c a refusé votre demande d'ami."
  friend_removed: "§cVous avez retiré §b{player}§c de vos amis."
  removed_by_friend: "§b{player}§c vous a retiré de ses amis."
  not_in_friends: "§eCe joueur n'est pas dans votre liste d'amis."
  already_blocked: "§eCe joueur est déjà bloqué."
  player_blocked: "§aVous avez bloqué §b{player}§a."
  you_are_blocked: "§cVous avez été bloqué par §b{player}§c."
  player_unblocked: "§aVous avez débloqué §b{player}§a."
  you_are_unblocked: "§aVous avez été débloqué par §b{player}§a."
  not_in_blocked: "§eCe joueur n'est pas dans votre liste de joueurs bloqués."
  friends_list_header: "§6--- Liste de vos amis ---"
  friends_list_empty: "§7Vous n'avez pas d'amis pour le moment."
  friends_list_entry: "§a- §b{player}"
  friends_list_footer: "§6------------------------"
  invalid_argument: "§cArgument invalide. Utilisez §e/friends <invite|accept|decline|remove|block|unblock|list> [joueur]"
  only_players: "§cSeuls les joueurs peuvent utiliser cette commande."
  config-reloaded: "§aConfiguration rechargée avec succès."
  max_friends_reached: "§cVous avez atteint la limite maximale d'amis."
  target_max_friends_reached: "§c{player} a atteint la limite maximale d'amis."
  bypass_enabled: "§aLe bypass de la limite d'amis est §2activé§a."
  bypass_disabled: "§cLe bypass de la limite d'amis est §4désactivé§c."
  no_permission: "§cVous n'avez pas la permission d'utiliser cette commande."
  friend_force_added: "§aVous avez ajouté {player} à votre liste d'amis en forçant la limite."
  friend_force_added_by: "§a{player} vous a ajouté à sa liste d'amis en forçant la limite."

plugin-info:
  version: "1.0.1"
  author: "TableIkea_"
  website: "https://github.com/Tablelkea/SocialManager"
settings:
    max_friends: 100

allow_self_friend: true